name = "app"
version = "0.1.0"

target = "javascript"

[dependencies]
gleam_stdlib = ">= 0.60.0 and < 2.0.0"
lustre = ">= 5.6.0 and < 6.0.0"

[dev-dependencies]
lustre_dev_tools = ">= 2.3.4 and < 3.0.0"
